spring:
  thymeleaf:
    cache: false
    mode: HTML5
  devtools:
    restart:
      enabled: true
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/drip?serverTimezone=UTC&characterEncoding=UTF-8
mybatis:
    mapper-locations: classpath:mapper/*.xml
server:
  port: 8080